up:
	pm2 start pm2.config.cjs

down:
	pm2 delete pm2.config.cjs

restart:
	pm2 restart pm2.config.cjs

stop:
	pm2 stop pm2.config.cjs

run:
	bun src/server.ts

log:
	pm2 logs be-api-generic-app

list:
	pm2 list